---
# tasks file for redis-ansible

- name: Install Redis
  apt:
    name: "{{ item.redis_package_version | ternary('redis-server=' + item.redis_package_version, 'redis-server') }}"
    update_cache: true
    cache_valid_time: 3600
  loop: "{{ redis_servers }}"

- name: Configure Redis servers
  include_tasks: configure.yml
  loop: "{{ redis_servers }}"
