# redis_servers variable is populated from ../inventory/host_vars/localhost
---
- hosts: localhost
  become: true
  connection: local
  tasks:
    - name: Install redis
      include_role:
        name: ../../../
