# redis_servers is populated directly from within the playbook
---
- hosts: localhost
  become: true
  connection: local
  vars:
    redis_servers:
      - redis_name: example1
        redis_port: 7979
      - redis_name: example2
        redis_port: 7980
  tasks:
    - name: Install redis
      include_role:
        name: ../../../
